name: GitHub Classroom Autograding
on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Buffer Logic Test
        uses: education/autograding-command-grader@v1
        with:
          test-name: Buffer Logic Test
          setup-command: npm install
          command: npm test
          timeout: 10
          max-score: 100
          
      - name: Autograding Reporter
        uses: education/autograding-grading-reporter@v1
        if: always()
        with:
          runners: Buffer Logic Test
